---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: git
    pull: always
    image: plugins/git:next
    settings:
      depth: 1

  - name: install
    depends_on: [git]
    pull: if-not-exists
    image: ubuntu:latest
    commands:
      - cd ./sandbox-sdk-app
      - npm install
      - npm install -g @angular/cli

  - name: tests-unit
    depends_on: [install]
    pull: if-not-exists
    image: ubuntu:latest
    commands:
      - cd ./sandbox-sdk-app
      - npm run test
    environment:
      CHROME_BIN: /usr/bin/google-chrome

  - name: tests-lint
    depends_on: [tests-unit]
    pull: if-not-exists
    image: ubuntu:latest
    commands:
      - cd ./sandbox-sdk-app
      - npm run lint

  - name: build
    depends_on: [tests-unit]
    pull: if-not-exists
    image: ubuntu:latest
    commands:
      - cd ./sandbox-sdk-app
      - npm run build --prod
