---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: git
    pull: always
    image: plugins/git:next
    settings:
      depth: 1

  - name: install
    depends_on: [git]
    pull: if-not-exists
    image: cypress/browsers:node12.14.1-chrome83-ff77
    commands:
      - cd ./sandbox-sdk-app
      - npm install
      - npm install -g @angular/cli

  - name: tests-unit
    depends_on: [install]
    pull: if-not-exists
    image: cypress/browsers:node12.14.1-chrome83-ff77
    commands:
      - cd ./sandbox-sdk-app
      - npm run test

  - name: tests-lint
    depends_on: [tests-unit]
    pull: if-not-exists
    image: cypress/browsers:node12.14.1-chrome83-ff77
    commands:
      - cd ./sandbox-sdk-app
      - npm run lint

  - name: tests-e2e
    depends_on: [tests-lint]
    pull: if-not-exists
    image: cypress/browsers:node12.14.1-chrome83-ff77
    commands:
      - cd ./sandbox-sdk-app
      - npm run e2e

  - name: build
    depends_on: [tests-lint]
    pull: if-not-exists
    image: cypress/browsers:node12.14.1-chrome83-ff77
    commands:
      - cd ./sandbox-sdk-app
      - npm run build --prod
