---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

trigger:
  event:
    - pull_request
    - tag

steps:
  - name: git
    pull: always
    image: plugins/git:next
    settings:
      depth: 1

  - name: install
    depends_on: [git]
    pull: if-not-exists
    image: node:12.11.1
    commands:
      - npm install

  - name: tests-lint
    depends_on: [install]
    pull: if-not-exists
    image: node:12.11.1
    commands:
      - npm run lint
      - echo fooasdasd

  - name: tests-unit
    depends_on: [install]
    pull: if-not-exists
    image: node:12.11.1
    commands:
      - npm run test

  - name: tests-unit
    depends_on: [install]
    pull: if-not-exists
    image: node:12.11.1
    commands:
      - npm run build --prod
