---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: git
    pull: always
    image: plugins/git:next
    settings:
      depth: 1

  - name: install
    depends_on: [git]
    pull: if-not-exists
    image: node:12.11.1
    commands:
      - cd ./sandbox-sdk-app
      - npm install
      - npm install -g angular-cli

  - name: tests-lint
    depends_on: [install]
    pull: if-not-exists
    image: node:12.11.1
    commands:
      - cd ./sandbox-sdk-app
      - npm run lint

  - name: tests-unit
    depends_on: [install]
    pull: if-not-exists
    image: node:12.11.1
    commands:
      - cd ./sandbox-sdk-app
      - npm run test

  - name: build
    depends_on: [install]
    pull: if-not-exists
    image: node:12.11.1
    commands:
      - cd ./sandbox-sdk-app
      - npm run build --prod
