---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: git
    pull: always
    image: plugins/git:next
    settings:
      depth: 1

  - name: install
    depends_on: [git]
    pull: if-not-exists
    image: node:12.11.1
    commands:
      - apt-get update
      - apt-get install -y curl unzip xvfb libxi6 libgconf-2-4
      - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      - apt-get -y update
      - apt-get -y install google-chrome-stable
      - google-chrome --no-sandbox &
      - cd ./sandbox-sdk-app
      - npm install
      - npm install -g @angular/cli

  - name: tests-lint
    depends_on: [install]
    pull: if-not-exists
    image: node:12.11.1
    commands:
      - cd ./sandbox-sdk-app
      - npm run lint

  - name: tests-unit
    depends_on: [tests-lint]
    pull: if-not-exists
    image: node:12.11.1
    commands:
      - cd ./sandbox-sdk-app
      - npm run test
    environment:
      CHROME_BIN: /usr/bin/google-chrome

  - name: build
    depends_on: [tests-unit]
    pull: if-not-exists
    image: node:12.11.1
    commands:
      - cd ./sandbox-sdk-app
      - npm run build --prod
